apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
spec:
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 10Gi
